#!/bin/bash
# Author: Mario Forzanini https://marioforzanini.com
# Date: 25/05/2021
# Description: Download and watch video lessons from ariel.unimi.it
# Dependencies: dmenu https://tools.suckless.org/dmenu mpv https://mpv.io,
# 		wget, youtube-dl https://www.youtube-dl.org

# Exit codes
EXIT_SUCCESS=0
EXIT_NO_DEPS=1
EXIT_NO_INPUT=2
EXIT_WRONG_ARG=3
EXIT_NOT_FOUND=4
EXIT_INTERRUPT=5

# File name for site's html code
INPUT_FILE=webpage.html

function no_dep() {
	printf "university-cli: $1 not found, install $1 to proceed"
	exit $EXIT_NO_DEPS
}

function no_file() {
	printf "university-cli: $1 not found, use -d to download it"
	exit $EXIT_NOT_FOUND
}

function no_download() {
	printf "$1 exists. Nothing to do."
	exit $EXIT_SUCCESS
}

function no_input() {
	printf "university-cli: No input file found: download the html page\
		in a file called $INPUT_FILE and retry"
	exit $EXIT_NO_INPUT
}

function check_webpage() {
	# Check for the existence of the input file
	test -e $INPUT_FILE || no_input

	# Variables
	VIDEOS=($(grep mp4 $INPUT_FILE | cut -d\" -f2))
	NAMES=($(grep mp4 $INPUT_FILE | cut -d\" -f2 | cut -d: -f3 | \
		sed 's/.mp4.*//'))

}


function download() {
	which youtube-dl>/dev/null || no_dep youtube-dl
	lesson=$(echo ${NAMES[@]} | sed 's/ /\n/g' | \
		dmenu -p "Download Lesson: " -i -l 10) || exit $EXIT_INTERRUPT

	test $lesson || no_file "$lesson".mp4
	test -e "$lesson".mp4 && no_download "$lesson".mp4

	youtube-dl --no-check-certificate $(grep "$lesson" $INPUT_FILE) -o \
		"$lesson.mp4" && exit $EXIT_SUCCESS
}

function download_all() {
	which youtube-dl>/dev/null || no_dep youtube-dl
	for i in ${!VIDEOS[@]}; do
		youtube-dl --no-check-certificate "${VIDEOS[$i]}" -o \
		"${NAMES[$i]}".mp4
	done && exit $EXIT_SUCCESS
}

function usage() {
	printf "Usage:\n\tuniversity-cli [OPTIONS] \
		\n\nAvailable options: \
		\n\t-h:\tDisplay this help message \
		\n\t-d:\tChoose a lesson to download \
		\n\t-D:\tDownload all videos \
		\n\t-v:\tChoose a lesson to watch\n"
}

function view() {
	which mpv>/dev/null || no_dep mpv
	lesson=$(echo ${NAMES[@]} | sed 's/ /\n/g' | \
		dmenu -p "Download Lesson: " -i -l 10) || exit $EXIT_INTERRUPT

	test $lesson || no_file "$lesson".mp4

	if test -z "$lesson.mp4"; then
		mpv $(grep $lesson $INPUT_FILE)
	else
		mpv $PWD/$lesson.mp4
	fi
	exit $EXIT_SUCCESS
}

# Read command line options
[ $# -eq 0 ] && usage
while getopts ":hDdv" o; do case "${o}" in
	h) usage
		;;
	d) check_webpage
	   download
		;;
	D) check_webpage
	   download_all
		;;
	v) check_webpage
	   view
		;;
	*) printf "Invalid option: -%s\\nTry -h for help\n" "$OPTARG" && \
		exit $EXIT_WRONG_ARG
		;;
esac
done
